name: Rosarium
favicon: null
layout_spectrum: 0.5908485669642687
typography_spectrum: 0.7954144119285047
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4076559441164136
  lightness: 0.21699680271558464
  saturation: 0.5363163000438362
  rhythmicContrast: 0.8357047953177243
purpose: []
