name: Rosarium
favicon: null
layout_spectrum: 0.00927
typography_spectrum: 0.78096
title: 'Rosarium | The Blog of Justin Bowen '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#251d22'
    - '#50484d'
    - '#6c0713'
    - '#a32b38'
    - '#f62e45'
  brandStrength: 0.5625
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0
purpose: []
